### ISSUE TITLE
Refactoring (master issue)

### ISSUE THREAD

**Issue by mvl22** [nptscot/nptscot.github.io#125]
This is a master ticket to track overall refactoring progress. Do not place new functionality requests here.

There is now a `refactor` branch, where all work is taking place, at:
https://github.com/nptscot/nptscot.github.io/commits/refactor

This is considered a stable branch and, following review, should be mergeable at any time.

Objectives:

- [x] Refactor layers to hoisted definitions
- [x] Remove jQuery dependency
- [x] Clear unused JS files
- [x] Encapsulate all code in functions
- [x] Fully split concerns, e.g. modals from charts
- [x] Migrate manual and pages to Markdown for easier editing
- [x] Remove all JS handlers from HTML file
- [x] Remove all CSS from HTML file
- [x] Convert basemap change to decoupled event-driven code
- [x] Combine .js files to single class (receiving definitions)
- [x] Enable `use strict` JS parser mode
- [x] Migrate definitions to an installation settings JS plus definition files
- [x] Extract layer-specific behaviour callbacks
- [x] Convert var to const/let
- [x] Remove all UI-specific namings within the logic
- [x] Standardise all HTML attribute namings

(Further objectives may be added.)

Removed objectives:

- Move JS dependencies to standard npm layouts and define in package.json (results in large volume of un-needed files; ideally we would use npm/Yarn, but the site currently is intended to be static).
- Potentially convert definition files to JSON
- Combine layer line colour definitions with legend colour definitions

**Comment by Robinlovelace** [comment]
:+1:

**Comment by mvl22** [comment]
All JS code is now encapsulated in functions, with clear splitting out of data from functionality, and most of it refactored into smaller chunks with distinct purposes.

There will next be a mass shifting of code into:

- A class containing all logic
- Definitions of layers etc
- System settings, e.g. tileserver

**Comment by mvl22** [comment]
Code is now combined into the three logical files:

https://github.com/nptscot/nptscot.github.io/tree/refactor/src

**Comment by Robinlovelace** [comment]
This is great progress, thanks Martin. Will make it easier to maintain, extend and generalise.

**Comment by mvl22** [comment]
> Standardise all HTML attribute namings

HTML input names and other HTML elements in the UI have now been standardised, as defined in a6501320a79fe498c445f0eabe8c8e89663688bf.

**Comment by Robinlovelace** [comment]
16 sub-issues down, 2 to go. Impressive work @mvl22!

All merged on dev version, biggest blocker to updating main website is out-of-date data now I think and that's in my court..

**Comment by mvl22** [comment]
> Potentially convert definition files to JSON

I'm not going to do this for now; I think this is probably an over-optimisation at this stage, and the definitions file is quite clear. Once there is any potential move to generate definitions out of the R side, we can come back to this.

**Comment by mvl22** [comment]
> Combine layer line colour definitions with legend colour definitions

This is pending on the broadband change, for which we have a ticket #142.

**Comment by mvl22** [comment]
The refactoring is basically done, so please do close this ticket.
